### ISSUE TITLE
Snacks not updating properly

### ISSUE THREAD

**Issue by RoyalCourt-lab** [ashah360/GrubNinja#2]
Yesterday I trained a pet on one wizard to adult. The next day, I logged in and logged on to another wizard. When I selected a pet on this second wizard, the stats of that pet were ??? instead of their normal numbers, and the snack selection belonged to my first wizard from yesterday. After feeding one snack from this other selection, the pet gained the EXP from the map it was on, but not the snack experience. The snack selection then updated to show the actual snacks belonging to the second wizard.

**Comment by CourDeRoyale** [comment]
Oh and these wizards are on the same account.

**Comment by ashah360** [comment]
Fixed in 1.1.4
